### PR TITLE
PR for #69

### LINKED ISSUE #69: Optimization: Fail early
When running `ansible-role-tester full`, the following lines are executed:

```
report.Ansible.Syntax = dist.RoleSyntaxCheck(&config)
report.Ansible.Run.Result, report.Ansible.Run.Time = dist.RoleTest(&config)
report.Ansible.Idempotence.Result, report.Ansible.Idempotence.Time = dist.IdempotenceTest(&config)
```

However, in the event of broken syntax or a broken ansible run, it doesn't make sense to try and continue these tests.

Ideally the program should fail fast when it encounters failed syntax or a failed run. The downside is the code will be a little more verbose with more checks. On the upside this will make the output more readable.

### PR DESCRIPTION
**Pull request by fubarhouse**
This PR resolves #69.

Changes:
* Flow control changes to prevent execution of specific pieces of functionality when the proceeding action fails for a fail-fast approach.

### CODE REVIEW

**Comment by issmirnov** [comment]
LGTM! The changes in #82 add an extra indentation, but hopefully it's not too hard to rebase your branch unto master.

```
git fetch
git checkout issue-69 
git rebase origin/master
# fix merge conflicts
git add -A
git commit 
git push --force
```

**Comment by fubarhouse** [comment]
Going to try and revisit this one in the next few days. 🙂

**Comment by fubarhouse** [comment]
Tests are now failing but if the application is exiting early it could be argued this is indicative of the behavior now triggering because the code prevents execution on failure of any step.

Perhaps a new flag could help get around this?

**Comment by issmirnov** [comment]
Hmm. I took a look and it seems to be passing locally if you flip the if conditions: https://github.com/issmirnov/ansible-role-tester/commit/10c2681a00e76fcdf85f6bd909783a6e053697b3

Want to give that a try?

**Comment by fubarhouse** [comment]
Looks good, fixes the weird anomaly I found but couldn't look into last night.
I've merged #114 into the source branch for this PR.

**Pull request merged**
